using Gedaq.Common.Enums;
using System;

namespace Gedaq.Npgsql.Attributes
{
    /// <summary>
    /// Attribute for generating batch request method
    /// </summary>
    /// <seealso href="https://github.com/SoftStoneDevelop/Gedaq.Npgsql/blob/main/Documentation/QueryBatch.md"/>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Method, AllowMultiple = true)]
    public sealed class QueryBatchAttribute : Attribute
    {
        /// <summary>
        /// 
        /// <see href="https://github.com/SoftStoneDevelop/Gedaq.Npgsql/blob/main/Documentation/QueryBatch.md"/>
        /// </summary>
        /// <param name="batchName">Name of the generated method</param>
        /// <param name="queryType">Type of generated query see <see cref="QueryType"/></param>
        /// <param name="methodType">Type of generated method see <see cref="MethodType"/></param>
        /// <param name="accessModifier">Access Modifier of Generated Methods see <see cref="AccessModifier"/></param>
        /// <param name="asyncResultType">The type of the generated Task/ValueTask see <see cref="AsyncResult"/> method</param>
        /// <param name="asPartInterface">The interface of which the generated method should be a part. It also generates descriptions of this method for the interface.</param>
        /// <param name="returnType">The type of the return collection that will be generated by the method. See <see cref="ReturnType"/></param>
        public QueryBatchAttribute(
            string batchName,
            QueryType queryType,
            MethodType methodType,
            AccessModifier accessModifier = AccessModifier.AsContainingClass,
            AsyncResult asyncResultType = AsyncResult.ValueTask,
            Type? asPartInterface = null,
            ReturnType returnType = ReturnType.List)
        {
        }
    }
}